name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Check prettier format
        run: npm run prettier:check

      - name: Install Railway CLI
        run: npm install -g railway

      # - name: Deploy to Railway
      #   run: railway up --service mi-escuela-primero --project mi-escuela-primero
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      #Railway detects pushes automatically, so we didnt need the last part lol
